var data = [
        {
            "Name": "Russian Blue Garnier Makeup Remover",
            "Price": "29.33",
            "Des": "<P>Ingredients: Aqua / water, hexylene glycol glycerin, disodium cocoamphodiacetate, disodium EDTA, poloxamer 184, biguanid polyaminopropyl (b162919 / 4).<br>  Garnier makeup remover with natural ingredients to clean sensitive, oily skin, prone to enlarged pores uses <br>&#10;- Effective in removing makeup from the face, eyes and lips.<br>&#10;- Gently clean, soothe your skin without friction as strong friction will easily damage the skin.<br>&#10;- Contains micelles with the ability to gently remove dirt and excess sebum on the skin, keeping the skin healthy</p>",
            "Features": "<p>OUR BEST MICELLAR WATER FOR YOU: You've seen micellar waters by Garnier on all the \"Best Drugstore Makeup Remover\" lists. Which Garnier Micellar Water is best for your skin type? Micellar water for Oily Skin? Makeup remover wipes for waterproof makeup?<br>GARNIER SKIN CARE: We developed Garnier SkinActive with gentle formulas to leave your skin looking fresh and healthy, no matter your skin type. Find the face wash, moisturizer, bb cream, makeup remover, eye cream, serum, or mask for you.</p>",
            "Specs": "Size: 1.36 x 2.26 x 4.56 inches",
            "By": "Russian",
            "No": "sk-1",
            "Type": "type-category-skin-tcfhtml",
            "Best": "ayes",
            "Catename": "Skin"
        },
        {
            "Name": "Russian Gold Garnier Makeup Remover",
            "Price": "27.34",
            "Des": "<P>Micellar water: A form of makeup remover applying Mixen technology with hydrophilic and oil-loving molecules (hydrophobic). The oil-loving head helps remove the makeup, while the hydrophilic head clings firmly to the cotton pad to remove makeup residue deep inside the pores while supplying water to the skin.<br>&#10;Glycerin: Helps provide moisture to the skin, helping to soften the skin after removing makeup.<br>&#10;<br>Hexylene Glycol: Helps to moisturize the skin.&#10;Disodium EDTA: Helps enhance the effectiveness of preservatives by stabilizing the pH of the product.<br>&#10;  Contains Argan oil that moisturizes dry skin and softens skin after use.</p>",
            "Features": "<P>Garnier brand was born in 1904 in Blois - a small province of beautiful France. The company uses ingredients extracted from nature such as fruits, nuts, ... safe for even sensitive skin. <br>Garnier Pure Active Micellar Cleansing Water is an oil-based makeup remover, used for all skin types, especially dry skin, deeply cleansing makeup.</p>",
            "Specs": "Size: 1.36 x 2.26 x 4.57 inches",
            "By": "Russia",
            "No": "sk-2",
            "Type": "type-category-skin-tcfhtml",
            "Best": "ayes",
            "Catename": "Skin"
        },
        {
            "Name": "Superfood Cleanser - Youth To The People",
            "Price": "27.34",
            "Des": "<P>- Vitamin C (THD Ascorbate): The latest clinically-proven form of stable, potent vitamin C works to firm and brighten the look of skin.<br>&#10;- Squalane and Hyaluronic Acid: Mimic your skin’s natural oils to boost skin hydration without the risk of clogged pores.<br>&#10;- Proprietary Superberry Blend: Antioxidant-rich, rare superberries hydrate and help combat free radicals.</p>",
            "Features": "<P>An overnight mask that thoroughly hydrates, plumps, and brightens with THD ascorbate (vitamin C), antioxidant-rich superberries, squalane, and hyaluronic acid.</p>",
            "Specs": "Size: 1.36 x 2.26 x 4.58 inches",
            "By": "Youth",
            "No": "sk-3",
            "Type": "type-category-skin-tcfhtml",
            "Best": "ayes",
            "Catename": "Skin"
        },
        {
            "Name": "Summer Fridays Jet Lag Mask",
            "Price": "48.12",
            "Des": "<P>You don’t have to be a jetsetter to have that lag. Upgrade your skin to a business-class complexion—no matter what time your red-eye gets in, or what time your head hits the pillow. This uber-dewy, hydrating mask is noncomedogenic and soothes thirsty, stressed-out skin by steeping it in a nourishing mix of vitamins, ceramides, antioxidants, and gently exfoliating extracts. Skin looks instantly renewed, radiant, and ready for anything.</p>",
            "Features": "<P>A one-of-a-kind hydrating cream face mask featuring proven, skin-loving ingredients that deliver rich hydration and a radiant complexion in just one application.</p>",
            "Specs": "Size: 1.36 x 2.26 x 4.59 inches",
            "By": "SUMMER",
            "No": "sk-4",
            "Type": "type-category-skin-tcfhtml",
            "Best": "no",
            "Catename": "Skin"
        },
        {
            "Name": "OLEHENRIKSEN Glow Motion™ 3-Piece Brightening Set",
            "Price": "50.33",
            "Des": "<p>- Polyhydroxy Acids (PHAs): A gentler alternative to AHAs that help even skin tone and texture through chemical exfoliation.<br>&#10;- Nordic Birch Sap: Helps hydrate and nourish skin.<br>&#10;- Pink Bentonite Clay: Helps clarify and renew.</p>",
            "Features": "<p>An age-fighting face mask that works like a facial, with potent PHAs and Nordic birch sap to exfoliate, illuminate, and brighten skin.</p>",
            "Specs": "Size: 1.36 x 2.26 x 4.60 inches",
            "By": "OLEHENRIKSEN",
            "No": "sk-5",
            "Type": "type-category-skin-tcfhtml",
            "Best": "no",
            "Catename": "Skin"
        },
        {
            "Name": "GLAMGLOW - SUPERMUD® Charcoal Instant Treatment Mask",
            "Price": "27.12",
            "Des": "<P>- Super Berry Blend: A mix of antioxidant-rich fruit extracts (blueberry, cranberry, and goji) and vitamins to nurture skin.&#10;- Lactobacillus Ferment Probiotic: Helps balance and support a healthy skin microbiome.<br>&#10;- Jojoba Oil, Hyaluronic Acid, and Shea Butter: Replenish hydration to visibly plump skin while protecting the skin’s moisture barrier.</p>",
            "Features": "<P>A moisturizing mask packed with super berries and probiotics to help repair skin’s moisture barrier.</p>",
            "Specs": "Size: 1.36 x 2.26 x 4.61 inches",
            "By": "GLAMGLOW",
            "No": "sk-6",
            "Type": "type-category-skin-tcfhtml",
            "Best": "no",
            "Catename": "Skin"
        },
        {
            "Name": "Fresh Rose Deep Hydration Sleeping Mask",
            "Price": "50.39",
            "Des": "<P>- Damask rose extract: Hydrates, smooths, and supports the skin’s natural moisture barrier.<br> - Advanced Time-Release Technology: Creates a tight-knit web on skin’s surface to gradually deliver moisturizing ingredients throughout the night.<br>&#10;- Hyaluronic Acid: Enhances suppleness with a plumping effect.</p>",
            "Features": "<p>A two-step mask that delivers continuous hydration overnight, drenching skin with moisture and then locking it in for a supple, dewy look.</p>",
            "Specs": "Size: 1.36 x 2.26 x 4.62 inches",
            "By": "Fresh",
            "No": "sk-7",
            "Type": "type-category-skin-tcfhtml",
            "Best": "no",
            "Catename": "Skin"
        },
        {
            "Name": "LANEIGE Special Care Water Sleeping Mask",
            "Price": "25.33",
            "Des": "<P>- Dryness<br> - Dullness and uneven texture<br>&#10;- Fine lines and wrinkles</p>",
            "Features": "<P>An overnight, moisture-recharging gel mask that quickly absorbs while you sleep to deeply hydrate skin.</p>",
            "Specs": "Size: 1.36 x 2.26 x 4.63 inches",
            "By": "LANEIGE",
            "No": "sk-8",
            "Type": "type-category-skin-tcfhtml",
            "Best": "no",
            "Catename": "Skin"
        },
        {
            "Name": "MAC Studio Fix Powder Plus Foundation NC20",
            "Price": "29.39",
            "Des": "<p> MAC's full name is Make-up Art Comestic with its headquarters located in New York City. <br> This brand was founded by two Canadians, Frank Toskan and Frank Angelo. <br> In 1991, the company opened its first store in New York. Initially, MAC designed products for professional make-up professionals, but now the brand is sold to all customers worldwide. In 1998, the MAC brand was managed by Estée Lauder Corporation after the death of its founder Frank Angelo in 1997. The characteristic of MAC is that most of MAC's products are oil-free, colorful and varied. Pioneers in making the latest makeup trends. <br> MAC is famous for its beauty, color grip, rich and diverse color palette, beautiful pictures suitable for runways, actors on stage and many women choose choose MAC for daily use.</p>",
            "Features": "<p>Makeup makes the girls more beautiful and adorable.  But most of the girls are often worried about whether regular makeup makes the skin ugly and damaged or not? However, now you can completely rest assured when coming to Mac Studio Fix Powder Plus Foundation.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "MAC LANEIGE",
            "No": "mk-1",
            "Type": "type-category-makeup-tcfhtml",
            "Best": "ayes",
            "Catename": "Make-up Kits"
        },
        {
            "Name": "Geo Sempre - Happy & Please Powder",
            "Price": "29.37",
            "Des": "<p>Geo Semper Happy & Please Powder with a thin, bright texture, gives a transparent makeup layer for all day long.<br> The powder is made up of empty powder chalks that both have a covering effect and high oil absorption, making the makeup layer naturally smooth, sticking evenly, and long-lasting.<br>&#10;&#10;Sunscreen SPF 20 helps to protect the skin from the effects of the sun.<br>&#10;&#10;Semper Happy & Please Powder is considered a product for connoisseurs with luxurious design like a pearl box with elegant lines throughout, will satisfy any lady. Come on.<br></p>",
            "Features": "<p>Geo Semper Happy & Please Powder with natural extracts with ingredients such as seawater, cactus, camellia, sea jelly and pearls are extremely skin-friendly, giving you fresh makeup bright, smooth. <br>&#10;&#10;Geo Semper Happy & Please Powder has the ability to alkaline oil, smooth the skin, not be moldy, making the makeup layer always dry.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Geo Sempre",
            "No": "mk-2",
            "Type": "type-category-makeup-tcfhtml",
            "Best": "ayes",
            "Catename": "Make-up Kits"
        },
        {
            "Name": "ILLA Lipstick - Funnel Of Love",
            "Price": "27.66",
            "Des": "<P>- Arginine (Keratin): Fortifies and nurtures lashes.<br>&#10;- Shea Butter: Weightlessly conditions lashes.<br>&#10;- Beeswax: Nourishes lashes.<br></p>",
            "Features": "<P>A clean, award-winning, cult-favorite mascara that lifts, lengthens, holds curl, and separates with precision.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "ILLA",
            "No": "mk-3",
            "Type": "type-category-makeup-tcfhtml",
            "Best": "no",
            "Catename": "Make-up Kits"
        },
        {
            "Name": "Too Faced - Natural Eyes Eye Shadow Palette",
            "Price": "27.66",
            "Des": "<P>Inspired by the curves of a woman’s body, the hourglass-shaped brush was designed with extra stiff bristles to maximize the performance of this carbon black, collagen-fueled formula. One coat and lashes are full and defined. Two coats and lashes are even more luscious, curled, and dramatic. Three coats help you achieve the most intense, black, multidimensional lashes possible.</p>",
            "Features": "<P>An intensely black voluptuous volume mascara for the sexiest, defined, multidimensional lashes possible.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Too Faced",
            "No": "mk-4",
            "Type": "type-category-makeup-tcfhtml",
            "Best": "no",
            "Catename": "Make-up Kits"
        },
        {
            "Name": "Lacome L’ABSOLU ROUGE DRAMA MATTE",
            "Price": "29.35",
            "Des": "<P> Free of sulfates SLS and SLES, formaldehydes, formaldehyde-releasing agents, phthalates, mineral oil, retinyl palmitate, oxybenzone, coal tar, hydroquinone, triclosan, and triclocarban, and contains less than one percent of synthetic fragrances.</p>",
            "Features": "<P>A nurturing eyelash primer that maximizes mascara results for major lash lift and the appearance of longer, thicker, and more volumized lashes.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Lacome",
            "No": "mk-5",
            "Type": "type-category-makeup-tcfhtml",
            "Best": "no",
            "Catename": "Make-up Kits"
        },
        {
            "Name": "Benefit Cosmetics Dandelion Twinkle Powder Highlighter",
            "Price": "27.34",
            "Des": "<P>This breakthrough bestseller reveals lashes you never knew you had! The specially designed brush features staggered bristles that grab close to the root, boosting length and volume beyond belief. The custom-domed tip uses precision bristles to lift, define, and curl even your tiniest lashes. With a glossy, jet-black, long-wearing formula, you’ll flaunt luxurious, silky lashes that won’t smudge, clump, or dry out.</p>",
            "Features": "<P>A lengthening mascara that curls, volumizes, lifts, and separates lashes for an \"out-of-here\" look.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Benefit",
            "No": "mk-6",
            "Type": "type-category-makeup-tcfhtml",
            "Best": "no",
            "Catename": "Make-up Kits"
        },
        {
            "Name": "Charlotte Tilbury Pillow Talk Diamonds",
            "Price": "29.33",
            "Des": "<P>- Diamond Powder: Infuses a jewel-like light to create a luminous and natural glow.<br>&#10;- Multilayered Pearl Pigments: Reflect light for a brilliant shine.</p>",
            "Features": "<P> A long-wear, gel-to-powder eyeshadow that has a soft, cream-like texture for a lightweight veil or pop of shimmer.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Charlotte",
            "No": "mk-7",
            "Type": "type-category-makeup-tcfhtml",
            "Best": "no",
            "Catename": "Make-up Kits"
        },
        {
            "Name": "Anastasia Beverly Hills Sultry Eyeshadow Palette",
            "Price": "27.88",
            "Des": "<P>This long-wearing clear gel sets and defines brows without fuss. The soothing chamomile formula also conditions hair and offers a lustrous, natural look.</p>",
            "Features": "<P>A clear gel for all hair colors that sets, defines, and holds brows in place all day.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Anastasia",
            "No": "mk-8",
            "Type": "type-category-makeup-tcfhtml",
            "Best": "no",
            "Catename": "Make-up Kits"
        },
        {
            "Name": "Living proof STYLE LAB FLEX HAIRSPRAY",
            "Price": "25.31",
            "Des": "<P>- Fast-Absorbing Powders: Soak up oil and sweat.<br>&#10;- Patented Healthy Hair Molecule: Reduces surface friction so it’s easy to remove the powders (and whatever they’ve soaked up) to keep hair cleaner, longer.<br>&#10;- Odor Neutralizers and Time-Release Fragrance: Create freshness and deliver a light scent all day.</p>",
            "Features": "<p>A dry shampoo that will actually clean your hair for you—removing dirt, oil, and odor for a fresh start—no shower necessary.</P>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Living proof",
            "No": "h-1",
            "Type": "type-category-hair-tcfhtml",
            "Best": "ayes",
            "Catename": "Hair"
        },
        {
            "Name": "Philosophy senorita margarita",
            "Price": "33.32",
            "Des": "<p>Suggested Usage: <br>&#10;-First dampen your hair or body, then slowly massage the gel into your hair or skin.&#10;-Rinse with warm water.<br>&#10;&#10;Precautions:<br>&#10;-For external use only.<br>&#10;-Use only as directed.>br>&#10;-Discontinue use if irritation occurs.<br>&#10;-Avoid direct contact with eyes.>br>&#10;-Keep out of reach of children.</p>",
            "Features": "<p>A three-in-one gel infused with the beloved Amazing Grace fragrance to leave you feeling amazingly clean and beautifully feminine.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Philosophy",
            "No": "h-2",
            "Type": "type-category-hair-tcfhtml",
            "Best": "ayes",
            "Catename": "Hair"
        },
        {
            "Name": "Kérastase Bain Elixir Ultime",
            "Price": "35.16",
            "Des": "<P>- Edelweiss Flower: Fills and strengthens fiber damage from within and resurfaces the cuticle for uniform porosity.<br>&#10;- Hyaluronic Acid: Softens and calms sensitized fibers.<br>&#10;- Ultra-Violet Neutralizers: Neutralize brassy and yellow tones.</P>",
            "Features": "<P>An ultra-violet, color-correcting shampoo made with hyaluronic acid that neutralizes lightened, cool-blonde, bleached, or grey hair. </P>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Kérastase",
            "No": "h-3",
            "Type": "type-category-hair-tcfhtml",
            "Best": "no",
            "Catename": "Hair"
        },
        {
            "Name": "Moroccanoli MOROCCANOIL TREATMENT LIGHT",
            "Price": "25.38",
            "Des": "<P>- ArganID™ Technology: Infuses the antioxidant powers of argan oil into hair while simultaneously helping to repair and seal the cuticle.<br>&#10;- Violet Pigments: Impart color and visual effect, enhancing depth, dimension, and providing a natural-looking sheen.</p>",
            "Features": "<P>A sulfate-free, tone-correcting shampoo to fight brassiness in blonde, lightened brunette, and grey hair.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Mor",
            "No": "h-4",
            "Type": "type-category-hair-tcfhtml",
            "Best": "no",
            "Catename": "Hair"
        },
        {
            "Name": "Briogeo Don’t Despair, Repair!",
            "Price": "25.13",
            "Des": "<P>- Cleanses and refreshes <br>&#10;- Detoxifies and draws out impurities<br>&#10;- Normalizes oil production</p>",
            "Features": "<P>A unique, charcoal-infused dry shampoo that detoxifies, cleanses, and balances the scalp for optimal scalp health. </p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Briogeo",
            "No": "h-5",
            "Type": "type-category-hair-tcfhtml",
            "Best": "no",
            "Catename": "Hair"
        },
        {
            "Name": "Drybar Detox Dry Shampoo",
            "Price": "34.16",
            "Des": "<P>- Micro-Fine Rice Powders: Absorb excess oils and odors, and as they absorb, they become translucent to naturally blend with all hair colors and expand to provide lift in the roots.<br>&#10;- Golden Root Extract: Increases moisture to prevent dryness and breakage.</p>",
            "Features": "<P>A super absorbent formula that eliminates oils and impurities, leaving hair looking and feeling clean and refreshed with extra volume and a matte finish.</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "Drybar",
            "No": "h-6",
            "Type": "type-category-hair-tcfhtml",
            "Best": "no",
            "Catename": "Hair"
        },
        {
            "Name": "SHANY Nail Art Set (24 Famous Colors Nail Art Polish, Nail Art Decoration)",
            "Price": "29.00",
            "Des": "<p>4 pearl, 4 neon, 11 matte, & 5 glitter shades<br>Quality above and beyond USA and CE, FDA standards<br>Durable design, Quick dry, Fine nail brush<br>No need to use a UV lamp, or LED lamp nail dryer<br>Works great with manicure pedicure accessories<br>&#10;Long lasting , yet affordable nailpolish<br>Quick dry formula, Use Top coat and base coat<br>This 24 piece nail art set has every color you need to design fabulous nails. Let your imagination run wild. Use the thin brush to create different patterns like feather strokes, checkered squares, rainbows, flowers and much more. *Tip* layer glitter over design to add sparkle. 1. Lime green (pearl) 2. Neon green 3. Yellow (matte) 4. Neon pink 5. Fuchsia (pearl) 6. Neon purple 7. Red (matte) 8. Neon yellow 9. White (matte) 10. Black (matte) 11. Silver (glitter) 12. Gold (glitter) 13. Pink (glitter) 14. Blue (glitter) 15. Green (glitter) 16. dark grey (matte) 17. Pink (matte) 18. Sky blue (matte) 19. Lavender (matte) 20. Brick (matte) 21. Navy (pearl) 22. Forest green (matte) 23. Orange (matte) 24. Purple (pearl)</p>",
            "Features": "<p>24 piece nail art set: 4 pearl shades, 4 neon shades, 11 matte shades, 5 glitter shades<br>Most wished for, most gifted nail art set. Quality above and beyond USA and CE, FDA standards<br>Durable design, Quick dry, Fine nail brush<br>No need to use a UV lamp, or LED lamp nail dryer<br>Works great with Shany nail art set, Nail brushes, Nail manicure pedicure accessories</p>",
            "Specs": "Size: 8.250\" X 6.250\" X 4.250\"",
            "By": "SHANY",
            "No": "na-1",
            "Type": "type-category-na-tcfhtml",
            "Best": "ayes",
            "Catename": "Nail Art"
        },
        {
            "Name": "SHANY 3D Nail Art Decoration Mini Bottles - 48 Glass Bottles",
            "Price": "12.00",
            "Des": "<p>48 Mini Glass Bottles, each bottle has 20 to 200 pieces<br>Individual bottles for easy portability<br>Glitters, sequins, and more included<br>Crushed shell, matte and neon colors & more<br>Free cosmetics Tweezers included inside the box<br>Mix and match the pieces to create your own look<br>Can be applied at top coat stage or any other stage<br>Have more options for nail art than you know what to do with! With this set, you get 48 individual bottles of assorted nail art and decorations. The individual bottles keep the different decorations easily separate, with caps that fit tightly so your accessories stay where you want them to. Each bottle contains a different kind, shape, and color of nail art, ranging from glitter to sequins to rhinestones and more. The colors also run the gamut, with pearlescent, glittery, and neon colors. Using these decorations is super easy, no matter your level of experience. Just use top coat or nail glue to apply them to your nails at any stage in the manicure or pedicure process and voila - fabulous nails!</P>",
            "Features": "<p>Set of 48 Mini Glass Bottles, each Glass bottle has 20 to 200 pieces inside<br>Individual bottles for easy portability - carry as many or as few as you need<br>Glitters, sequins, rhinestones , 3D nail art , powders and more included<br>Includes pearly, glittery, crushed shell, matte and neon colors in various shapes<br>Free cosmetics Tweezers included inside the box for easy nail art application</p>",
            "Specs": "Size: 8.000\" X 6.250\" X 0.500\"",
            "By": "SHANY",
            "No": "na-2",
            "Type": "type-category-na-tcfhtml",
            "Best": "ayes",
            "Catename": "Nail Art"
        },
        {
            "Name": "SHANY DIY 3D Nail Art Set - 72 Assorted Designs, Jewelries, Powder, Glitter - Nail Fanatic Collection",
            "Price": "15.00",
            "Des": "<p>Selection of 72 assorted nail art designs.<br>Can be used on natural or false nail tips<br>Application is very easy<br>Assorted nail art shapes, crushed powder & more<br>Dimensions: 1\" in diameter. Comes with organizer box<br>Create you own style of nail art.<br>Mix and match with other nail art decorations<br>Does your sense of artistry as high as us? Then try our new set of Nail decorations .This set includes 72 cherry picked containers. This set includes glitter, stones, 3D art pieces, jewelries, powders and many more options. Each container is individually packed. Easily applied to nails, regardless of user’s level of experience. The colors are gorgeous and carry over very well. They last for a very long time. Great for beginners and also professionals. They can be used on natural or false nail tips and suitable for manicures and pedicures. Application is very easy and is described within the product. The jars are crystal clear which makes it easy to distinguish and use. The see through box makes a perfect storage for the product as well. Apply them to your nails at any stage in the manicure or pedicure process and voila - fabulous nails!</p>",
            "Features": "<p>Make your nails beautiful and elegant with the selection of 72 assorted nail art designs.<br>They can be used on natural or false nail tips and suitable for manicures and pedicures.<br>Application is very easy and is described within the product. Use them with shany nail art set.<br>Assorted nail art shapes, 3d designs, crushed powder, Nail rhinestones, Nail art decorations.<br>Dimensions: 1\" in diameter. Comes with a cosmetics organizer box for easy storage.</p>",
            "Specs": "Size: 12.250\" X 11.000\" X 1.000\"",
            "By": "SHANY",
            "No": "na-3",
            "Type": "type-category-na-tcfhtml",
            "Best": "ayes",
            "Catename": "Nail Art"
        },
        {
            "Name": "Empire Collection Nail Art Pens Set Varnish Polish Decorate Design Nails (21 Pens Full Collection)",
            "Price": "19.49",
            "Des": "<p>Nail Art Pens Set Varnish Polish Decorate Design Nails Supreme Mix and match colours to suit your taste. FUN & EASY The nail art pens come in a hard carton box with instructions leaflet. Each part of the pen (one colour) holds 4.8ml of polish and has a thin metal tip for precision drawing and a classic nail polish brush for painting whole nail. Another cool thing about these is that you can take them apart and combine different colours together so if you're for example going on holiday and want to take just two or four colours you can simply screw the chosen ones together. Each style has six pens and you can select from Classic, Original Neon and Neon Gems. We recommend selecting \"21 Pens Full Collection\" for a nice selection.</p>",
            "Features": "<p>Select from Original , Classic , Neon, Neon Gems or Full Collection 21 Pen Set<br>Decorate Design Nails With Nail Polish<br>FUN & EASY<br>Mix & Match Colours<br>Features Brush & Pointed Nib</p>",
            "Specs": "Size: 21 Pens Full Collection",
            "By": "PREMIER PORTFOLIO",
            "No": "na-4",
            "Type": "type-category-na-tcfhtml",
            "Best": "no",
            "Catename": "Nail Art"
        },
        {
            "Name": "Kangler Nail Art Pens, 16 Colors Nail Art Pen for 3D Nail Art DIY Decoration",
            "Price": "26.99",
            "Des": "<p>Nail Art Pens give you the opportunity to create professional-looking nail art in your own home. The fine tip allows for precise control while you design your own manicure rivaling nail wraps and professional manicurists.<br>Nail Art Pens are available in 16 gorgeous colors to complement your day wear, work wear, evening wear, date night, little black dress, jeans and t-shirt, sundress, bikini, shorts & tank top, club outfit, suit & tie or any look!<br>A precise, fine-tipped nail pen, Nail Art Pens help you create the perfect manicure for any occasion: day, work, or evening! Color your day with Kangler Nail Art Pens.<br>Made of Water-based environmentally friendly resin, which is water-based formula wipes off easily. Miracle Gel Nail Polish is the closest thing you can get to a salon manicure at home, no UV lamp required! Just apply a basecoat and top coat of your favorite color, let it dry, and finish with Miracle Gel Top Coat.</p>",
            "Features": "<p>Very simple, everybody can control it.<br>The more colors you have, the more patterns you can make on your nails.<br>The pigment is made of high-end materials. The quality is great.<br>It is absolutely safe for you to use them.<br>Please be assured to use them and make your own design of your nail pattern.</p>",
            "Specs": "Package Dimensions : 6.3 x 4.1 x 2.1 inches",
            "By": "Kangler",
            "No": "na-5",
            "Type": "type-category-na-tcfhtml",
            "Best": "no",
            "Catename": "Nail Art"
        },
        {
            "Name": "Bella Voste Sugar Baby Nail Paints Shade 361 (10 ml)",
            "Price": "1.99",
            "Des": "<p>Imagine an invigorating colorful fairytale! Magnify your fashion quotient with our exclusive range of rich nail enamel shades! Steal the show with a striking finish that's brimming with flamboyance<br> The unique nail enamel formula is 10 Toxic Free and is suitable for all types and every occasion<br> Give yourself all the attention that you truly deserve</p>",
            "Features": "<p>Chip Resistant, Consistent Shade, Dries quickly, Durable<br>Easy Application, Easy Layering, Even Color Payoff, Glides easily, High Color Payoff, Highly Pigmented, Intense Pigmentation, Long Lasting<br>Luminous, Moisturizing, Non-Patchy, Non-Yellowing, Precise Application, Shimmery Effect<br>Single Stroke Application, Smooth Application, Strengthening, Strengthens The Nails, Strong Packaging</p>",
            "Specs": "Product Specs:<br>Skin Concern: Chipped Nails<br>Makeup Color Family: Silver",
            "By": "Bella Voste",
            "No": "np-1",
            "Type": "type-category-np-tcfhtml",
            "Best": "ayes",
            "Catename": "Nail Paint"
        },
        {
            "Name": "Bella VosteLuxe Cookies Shade 242 (10 ml)( PEEL-OFF)",
            "Price": "1.99",
            "Des": "<p>Imagine an invigorating colorful fairytale! Magnify your fashion quotient with our exclusive range of rich nail enamel shades! Steal the show with a striking finish that's brimming with flamboyance<br> The unique nail enamel formula is 10 Toxic Free and is suitable for all types and every occasion<br> Give yourself all the attention that you truly deserve</p>",
            "Features": "<p>DBP Free, Formaldehyde Free, Toluene Free, Toxicity Free<br>Chip Resistant, Consistent Shade, Dries quickly, Durable<br>Easy Application, Easy Layering<br>Luminous, Moisturizing, Non-Patchy, Non-Yellowing<br>Single Stroke Application, Smooth Application, Strengthening, Strengthens The Nails, Strong Packaging</p>",
            "Specs": "Product Specs:<br>Skin Concern: Chipped Nails<br>Makeup Color Family: Pink",
            "By": "Bella Voste",
            "No": "np-2",
            "Type": "type-category-np-tcfhtml",
            "Best": "no",
            "Catename": "Nail Paint"
        },
        {
            "Name": "Bella Voste Gold Glitter Nail Paint (10 ml)",
            "Price": "0.99",
            "Des": "<p>Imagine an invigorating colorful fairytale! Magnify your fashion quotient with our exclusive range of rich nail enamel shades! Steal the show with a striking finish that's brimming with flamboyance<br> The unique nail enamel formula is 10 Toxic Free and is suitable for all types and every occasion<br> Give yourself all the attention that you truly deserve</p>",
            "Features": "<p>DBP Free, Formaldehyde Free, Toluene Free, Toxicity Free<br>Chip Resistant, Consistent Shade, Dries quickly, Durable<br>Easy Application, Easy Layering<br>Luminous, Moisturizing, Non-Patchy, Non-Yellowing<br>Single Stroke Application, Smooth</p>",
            "Specs": "Product Specs:<br>Skin Concern: Chipped Nails<br>Makeup Color Family: Golden",
            "By": "Bella Voste",
            "No": "np-5",
            "Type": "type-category-np-tcfhtml",
            "Best": "no",
            "Catename": "Nail Paint"
        },
        {
            "Name": "Purplle Nail Lacquer, Nude, Creme - High On Latte 7 (9 ml)",
            "Price": "1.49",
            "Des": "<p> Give your nails their best friend in the form of Purplle's Nail Lacquer<br>A unique range with a creme finish, this shade gives your nail the ultimate look you're looking for<br> Perfectly safe for your nails, this beauty comes with a brush, helping you to apply the colour in One go<br> Just like a true friend, this shade stays for a long time and gives you an unforgettable finish<br> Its time to express yourself with different shades everytime you step out of the house</p>",
            "Features": "<p>Chip Resistant, Consistent Shade, Consistent Texture<br>Dries quickly, High Color Payoff, Long Lasting<br>Precise Application, Shine, Single Stroke Application, Smudgeproof</p>",
            "Specs": "Product Specs:<br>Makeup Color Family: Neutrals & Nudes",
            "By": "Purplle",
            "No": "np-3",
            "Type": "type-category-np-tcfhtml",
            "Best": "no",
            "Catename": "Nail Paint"
        },
        {
            "Name": "NY Bae Brighten up your 'gram Nail Lacquer Neon Mauve 7",
            "Price": "0.69",
            "Des": "<p>Designed to make your nails stand out with confidence like a pro, NY Bae’s Brighten up your ‘gram Nail Lacquers are just the right pick for your beautiful and dainty looking nails! Choose from a variety of different colours and light up that spark to your NY Bae look<br> Designed to style your nails like a fashionista with a rich colour in one swipe<br> Made to last long without chipping off so that your nail’s shade is the center of NY’s most loved looks! &nbsp;&#10;</p>",
            "Features": "<p>What’s an NY look without some sass &amp; gloss over the nails? NY Bae lets you add definition and style to your fingertips with Brighten up your ‘gram Neon Mauve Nail Lacquer. Designed to give your nails a rich colour in a single swipe application without letting it chip off, this nail lacquer gives you and your nails the confidence to walk down the streets with charm and elegance!  </p>",
            "Specs": "Product Specs:<br>Makeup Color Family: Purples<br>Finish: Glossy Finish",
            "By": "NY Bae",
            "No": "np-4",
            "Type": "type-category-np-tcfhtml",
            "Best": "no",
            "Catename": "Nail Paint"
        },
        {
            "Name": "Freshwater Pearl Ring in Sterling Silver",
            "Price": "600.00",
            "Des": "<p>Tiffany HardWear is elegantly subversive and captures the spirit of the women of New York City. Two bold bands of sterling silver exude modern sophistication in this double ring design.</p>",
            "Features": "<p>Sterling silver with a freshwater cultured pearl<br>Designed to be comfortable and easy to wear</p>",
            "Specs": "Product Specs: Pearl, 9.5-10 mm",
            "By": "Tiffany HardWear",
            "No": "j-1",
            "Type": "type-category-jewel-tcfhtml",
            "Best": "no",
            "Catename": "Jewellry"
        },
        {
            "Name": "T1 Narrow Diamond Ring",
            "Price": "1600.00",
            "Des": "<p>Pavé diamonds illuminate one side of this ring, adding a striking radiance to the design. A reinvention of a Tiffany icon, Tiffany T1 designs represent individual strength and perpetual power, worn outwardly to express what lies within. Style this ring with other Tiffany designs in 18k rose gold or mix your metals for a striking look.</p>",
            "Features": "<p>18k rose gold with round brilliant diamonds<br>2.5 mm wide</p>",
            "Specs": "Product Specs: Carat total weight .08",
            "By": "Tiffany T1",
            "No": "j-2",
            "Type": "type-category-jewel-tcfhtml",
            "Best": "ayes",
            "Catename": "Jewellry"
        },
        {
            "Name": "Diamond Vine Bypass Ring in Platinum",
            "Price": "16000.00",
            "Des": "<p>Inspired by the fire of our superlative diamonds, Tiffany Victoria® designs are intricately handcrafted with a unique combination of cuts. These delicate cluster earrings, rings, bracelets and necklaces in platinum, 18k white gold and rose gold are intricately set with pear, round and marquise diamonds that shine with unrivaled intensity.<br>With an intensity that rivals the night sky, Tiffany Victoria celebrates the blazing brilliance of Tiffany diamonds. The organic vine motif of this bypass ring complements the beauty of mixed-cut diamonds.</p>",
            "Features": "<p>Platinum with round brilliant and marquise diamonds</p>",
            "Specs": "Product Specs: Carat total weight 1.19",
            "By": "Tiffany Victoria",
            "No": "j-3",
            "Type": "type-category-jewel-tcfhtml",
            "Best": "ayes",
            "Catename": "Jewellry"
        },
        {
            "Name": "Elisa Gold Open Frame Crystal Pendant Necklace In Gold",
            "Price": "100.00",
            "Des": "<p>Our #1 best seller and a little bit of sparkle? The perfect combination! The Elisa Open Frame Crystal Pendant Necklace in Gold if you're looking to dress up your look in a glamorous, yet totally wearable way.</p>",
            "Features": "<p>Metal: 14k Gold Plated Over Brass<br>Closure: Adjustable lobster claw</p>",
            "Specs": "Siza: 0.754\" L X 0.5\" W station, 18\" chain",
            "By": "Kendra Scott",
            "No": "j-4",
            "Type": "type-category-jewel-tcfhtml",
            "Best": "no",
            "Catename": "Jewellry"
        },
        {
            "Name": "Karina Statement Earrings In Gold",
            "Price": "99.00",
            "Des": "<p>A feather-inspired statement silhouette loved for its modern bohemian feel, we are thrilled to bring the Karina Earrings in Gold back from our design vault for a limited time.</p>",
            "Features": "<p>Metal: 14K Gold Plated Over Brass</p>",
            "Specs": "Siza: 2.375\"L X 1.75\"W on earwire",
            "By": "Kendra Scott",
            "No": "j-5",
            "Type": "type-category-jewel-tcfhtml",
            "Best": "no",
            "Catename": "Jewellry"
        },
        {
            "Name": "Beaded Detail Square Neck Sleeveless Crepe Midi Dress",
            "Price": "218.40",
            "Des": "<p>It is an emblem of the purity and innocence of girlhood, and the unsullied heart she now yields to the chosen one.” Victorian ideals of weddings, romantic love, and purity were projected backwards to rewrite the white dress as a symbol of innocence and virginity rather than wealth.</p>",
            "Features": "<p>From Adrianna Papell, this gown features:<br>Crepe fabrication<br>square neckline<br>Sleeveless<br>beaded button front detail<br>Princess seaming<br>Fully lined<br>Zip back closure<br>Approx. 58.75\" length<br>Polyester<br>Spot clean</p>",
            "Specs": "SIZE: 0, 2, 4, 6, 8, 10&#10;<br> COLOR: WHITE",
            "By": "Adrianna Papell",
            "No": "wd-1",
            "Type": "type-category-wedding-tcfhtml",
            "Best": "ayes",
            "Catename": "Wedding Kits"
        },
        {
            "Name": "Barbara V-Neck Crossover Waist Slit Front Leg Jumpsuit",
            "Price": "162.43",
            "Des": "<p>Fit-and-flare gowns are flattering on many different body types, which is why they're among the most popular wedding dress shapes. This silhouette looks incredible when paired with a sweetheart or deep V-neckline.</p>",
            "Features": "<p>From Alex Marie, this jumpsuit features:<br>split v-neckline<br>sleeveless styling<br>crossover waist detail<br>slit front leg hem<br>floor-length pant<br>invisible back zipper closure<br>polyester/elastane<br>dry clean</p>",
            "Specs": "SIZE: 0, 2, 4, 6, 8, 10&#10;<br> COLOR: WHITE",
            "By": "Alex Marie",
            "No": "wd-2",
            "Type": "type-category-wedding-tcfhtml",
            "Best": "ayes",
            "Catename": "Wedding Kits"
        },
        {
            "Name": "Off-the-Shoulder Floral Embroidered Tulle A-Line Midi Dress",
            "Price": "535.58",
            "Des": "<p>Though in history the wedding dress came to represent the end of a woman's identity as an individual and a move to being a dependent wife, it now importantly signifies the end of singlehood to a new commitment and partnership.</p>",
            "Features": "<p>This dress from Tadashi Shoji features:<br>boat neckline<br>Cap sleeves<br>Floral embroidery<br>Zip-back closure<br>Approx. 44.5\" length from shoulder to hem<br>Rayon/Polyester/Nylon<br>Fully lined petal pink polyester<br>Dry clean only</p>",
            "Specs": "SIZE: 0, 2, 4, 6, 8, 10&#10;<br> COLOR: WHITE",
            "By": "Tadashi Shoji",
            "No": "wd-3",
            "Type": "type-category-wedding-tcfhtml",
            "Best": "no",
            "Catename": "Wedding Kits"
        },
        {
            "Name": "Beaded Soutache V-Neck Illusion 3/4 Bell Sleeve Dress",
            "Price": "349.00",
            "Des": "<p>The color of your wedding dress is said to determine the quality of your marriage. Yellow, grey, green, pink, red and black are all supposed unlucky colors</p>",
            "Features": "<p>From JS Collections, this dress features<br>sheath silhouette<br>v-neckline<br>3/4 bell sleeves<br>embroidered detail<br>straight hemline<br>back zipper closure<br>approx. 40\" length<br>nylon<br>spot clean</p>",
            "Specs": "SIZE: 0, 2, 4, 6, 8, 10&#10;<br> COLOR: WHITE",
            "By": "JS Collections,",
            "No": "wd-4",
            "Type": "type-category-wedding-tcfhtml",
            "Best": "no",
            "Catename": "Wedding Kits"
        },
        {
            "Name": "One Shoulder Odessa Crepe Gown",
            "Price": "762.76",
            "Des": "<p>Aim to order your gown no later than 6-7 months prior to your wedding date, in order to avoid rush fees and leave adequate time for production and fittings. It's important to remember: Most bridal gowns are made-to-order.</p>",
            "Features": "<p>From Badgley Mischka, this gown features:<br>Odessa Crepe Fabrication<br>Asymmetric/One-Shoulder Neckline<br>3/4 Sleeves<br>Full Zip Back Closure<br>approx. 61\" Length<br>Dry Clean<br>Polyester</p>",
            "Specs": "SIZE: 0, 2, 4, 6, 8, 10&#10;<br> COLOR: WHITE",
            "By": "Badgley Mischka",
            "No": "wd-5",
            "Type": "type-category-wedding-tcfhtml",
            "Best": "no",
            "Catename": "Wedding Kits"
        },
        {
            "Name": "Ruffled Crepe Cocktail Dress",
            "Price": "219.94",
            "Des": "<p>A-line wedding dress is characterized by the silhouette of the skirt. An A-line skirt is fitted at the hips and gradually flares out from the natural waistline of the bodice towards the hem. ... An A-line dress can feature any length of train.</p>",
            "Features": "<p>From Aidan Aidan Mattox, this dress features:<br>Crepe fabrication<br>Sheath silhouette<br>V-Neck<br>Sleeveless<br>Ruffle detail at shoulders<br>Fully lined<br>Ruffled flounce hem<br>Zip back closure<br>Approx. 35.5\" length<br>Polyester<br>Dry clean only</p>",
            "Specs": "SIZE:  10, 12, 14&#10;<br>COLOR: WHITE",
            "By": "Aidan Aidan Mattox",
            "No": "wd-6",
            "Type": "type-category-wedding-tcfhtml",
            "Best": "no",
            "Catename": "Wedding Kits"
        },
        {
            "Name": "Sequined Leaf Off-the-Shoulder Sheath Dress",
            "Price": "130.88",
            "Des": "<p>In many societies the color white has long been associated with purity and virtue, and that is one reason why some brides choose to wear white, especially in the West. ... Brides tended to buy a wedding dress that could be worn again, or they simply wore the best dress they already owned.</p>",
            "Features": "<p>From Adrianna Papell, this dress features:<br>Sheath silhouette<br>Off-the-shoulder neckline<br>Cap sleeves<br>Sequined leaf motif<br>Zip back closure<br>Approx. 20\" length from natural waist<br>Polyester<br>Dry clean only</p>",
            "Specs": "SIZE:  16&#10;<br>COLOR: WHITE",
            "By": "Adrianna Papell",
            "No": "wd-7",
            "Type": "type-category-wedding-tcfhtml",
            "Best": "no",
            "Catename": "Wedding Kits"
        },
        {
            "Name": "Mini Masterpiece Makeup Set - 6 Layer Refills - CONTOUR",
            "Price": "10.00",
            "Des": "<p>The Mini Masterpiece 6 Layer Makeup Set is an all-in-one contour and highlighting makeup kit with removable and interchangeable layers of face palettes. The first layer comes with six pans of blendable, cream foundation and contour makeup, which also includes cream highlighting shades. Next, the second layer holds with 11 round pans of cream concealer makeup, which also includes four color correctors in the shades: lavender, peach, yellow, and green. The third layer comes with six pans of buttery powder contour makeup, which also includes bronzer and highlighting shades. The fourth layer houses six pans of powder blush makeup, which includes shimmer and matte shades in cool and warm tones. This fifth layer comes with another six pans of blendable, powder blush makeup, which includes shimmer and matte shades in cool tones. The final and sixth layer comes with the last six pans of powder blush makeup, which includes shimmer and matte shades in warm tones. This set comes with a sturdy box to arrange and store each palette layer. Refill palettes are available for this set to replace your most loved layers. This product was designed by beauty professionals in the USA.</p>",
            "Features": "<p>Best contour makeup kit for novices, enthusiasts, and professionals of different ages<br> One layer of blendable foundation/contour/ highlight creams for different skin tones<br>One layer of matte contour and highlighting powder foundations (warm and cool toned)<br> One layer of 12 mini cream concealer and contouring shades, two color correctors, and a highlight<br>SHANY is a member of PETA and of our products are cruelty-free – pair this set with our professional-quality brushes for best application.</p>",
            "Specs": "SKU: SHTR-6L-01 <br>WEIGHT: 0.28 lb <br>COLOR: CONTOUR",
            "By": "SHANYnation",
            "No": "upc-1",
            "Type": "type-category-upcoming-tcfhtml",
            "Best": "no",
            "Catename": "Upcoming Products"
        },
        {
            "Name": "4-Layer Contour and Highlight Makeup Kit",
            "Price": "40.00",
            "Des": "<p>The SHANY 4-Layer Contour and Highlighting Makeup Set is the perfect set for contouring beginners and professionals. The user-friendly kit houses four palettes with all your contour needs. In the first layer, you will find 15 blendable, cream concealer makeup, including color correctors to cancel out redness, dark under eyes, or yellow pigmentation. The second layer includes six high-quality cream contour shades, that can also be used as foundation. If you prefer powder, or setting your makeup for longer wear, the third layer has the same six shades in a pressed powder formula. Slide out the fourth and final layer to reveal six vibrant, powder blush shades that go with any skin tone. Use our SHANY professional-quality brushes for the best application.</p>",
            "Features": "<p>This layered makeup set contains four contour palettes made to be used by makeup beginners or professionals of all ages for a flawless, airbrushed effect.<br> Slide out first cream foundation/concealer palette to reveal 15 concealer and color corrector shades in a smooth, creamy formula that cover imperfections seamlessly for a perfect, airbrushed look.<br> The next two layers are made to define and highlight your face, with six illuminating creams and six face powder contour shades. Perfect to use as foundation, bronzer makeup, and highlighting powder to mimic higher cheekbones.<br> Simply finish off your gorgeous contour look by choosing your favorite blusher shade from the six beautiful, powder shades in the blush palette in the final layer of this step-by-step contouring makeup set for a beautifully sculpted look.<br> SHANY is a proud member of PETA and all of our products are 100% cruelty-free. Our four layer contour and highlight makeup gift set can be used with our beauty blender puffs. This cream contour kit was designed by beauty professionals in the USA.</p>",
            "Specs": "SKU: SH-K4L <br>WEIGHT: 1.13 lb",
            "By": "SHANYnation",
            "No": "upc-2",
            "Type": "type-category-upcoming-tcfhtml",
            "Best": "no",
            "Catename": "Upcoming Products"
        },
        {
            "Name": "Nail Polish Set with 12 Semi Glossy and Shimmery Finishes - ROSE",
            "Price": "20.00",
            "Des": "<p>The SHANY Nail Polish collection is a professional-quality varnish set inspired by beautiful shades and created for 1-coat finishes. Each nail polish comes in a .5 fluid oz. bottle that’s big enough for multiple uses, yet small enough for travel and on-the-go practice. These gorgeous shades are highly-pigmented and can range from medium to full coverage. The nail polishes were made with a buildable, chip-resistant, and bubble-free formulation that makes them ideal for personal and professional use. They come in semi-glossy, glittery, and metallic finishes.\"</p>",
            "Features": "<p>The nail polish set contains a full size collection with twelve 0.5 fl. oz. bottles of gorgeous semi-glossy nail polish colors.<br>Each eye-catching color was inspired by a beautiful shade and created for easy 1-coat finishes that provide full coverage.<br> The highly-pigmented nail polishes allow for buildable coverage, while also providing both semi-glossy and shimmery finishes.<br> Specially designed with a semi-quick dry formulation, these nail polishes are chip-resistant. bubble-free, and made for longtime wear.<br>This gift set comes in a nail polish organizer tray. SHANY is a proud member of PETA and all of our products are 100% cruelty-free.</p>",
            "Specs": "SKU: SH-SHNN-1 <br>WEIGHT: 1.15 lb <br>COLOR: ROSE",
            "By": "SHANYnation",
            "No": "upc-3",
            "Type": "type-category-upcoming-tcfhtml",
            "Best": "no",
            "Catename": "Upcoming Products"
        },
        {
            "Name": "Seventh Heaven Professional Manicure/Pedicure Tweezer Set",
            "Price": "10.00",
            "Des": "<p>The SHANY Seventh Heaven Manicure/Pedicure Tweezer Set is a 7-piece set of tools ideal for manicure, pedicure, and eyebrows. In a beautiful shade of purple, these professional grooming tools are placed in travel carrying case with silicone tips to prevent dullness. To provide sturdiness and long-lasting ability, these eyebrow plucking instruments are made from stainless steel. This tweezer gift set contains slant tip tweezers, pointed tweezers, and curved brow scissors. These tweezers are perfectly organized and convenient for traveling purposes. This all-in-one manicure and pedicure tweezer kit is perfect nail and cuticle trimming, nail grooming, nail art placement, and eyebrow maintenance. These precision eyebrow tweezers are also ideal for ingrown hair, tick removal, and splinter removal. Designed by beauty professionals in the USA.\"</p>",
            "Features": "<p>This perfectly purple all-in-one manicure and pedicure tweezer set is a professional grooming kit for convenient facial, nail and cuticle repairing and trimming.<br> These seven nail care and eyebrow plucking tools, placed in a travel case, are made from durable anti-static stainless steel to provide sturdiness and long-lasting ability.<br> In a stylish purple shade, these tools in this tweezer gift set are ideal for eyebrow maintenance, trimming cuticles, ingrown hair removal, splinter removal and tick removal.<br> These precision eyebrow tweezers are organized in one spot in durable carrying case. This set contains slant tip tweezers, pointed tweezers, and curved nail scissors for grooming.<br> SHANY is a proud member of PETA and all of our products are 100% cruelty-free. This 7-piece all-in-one manicure/pedicure hair removal tweezer set was designed by beauty professionals in the USA.</p>",
            "Specs": "Size: 6.000\" X 6.000\" X 0.800\"",
            "By": "SHANYnation",
            "No": "upc-4",
            "Type": "type-category-upcoming-tcfhtml",
            "Best": "no",
            "Catename": "Upcoming Products"
        },
        {
            "Name": "(Not So) Sweet Sixteen Creme Lipstick Set - 16 Varying Colors",
            "Price": "25.00",
            "Des": "<p> The SHANY (Not So) Sweet Sixteen Creme Lipstick Set is the perfect set for all lipstick lovers. In this set, there are 16 hydrating and vibrant lip shades. Each rich shade is long-lasting and fits every style and occasion. These highly pigmented shades are easy to apply with their creamy formula. In a perfect gift box, each shade is easy to find with peek-a-boo packaging on the lids. Each lipstick stands at 3.5-inches and come in a variety of shades from natural pinks to dark berries. </p>",
            "Features": "<p> Express yourself with these 16 highly pigmented and moisturizing lipsticks that come in a variety of shades for any occasion.<br> Open the top of the box to reveal all of the bold, vivid lip colors that start with natural pinks and go all the way to dark berry shades.<br> Perfect for all makeup lovers, from professionals to newbies, and work for every style and occasion with their hydrating formula that is long-lasting.<br> These lipsticks stands at 3.5 in., with peek-a-boo packaging to make the 8 pinks, 4 reds, 3 purples, and 1 orange shade easy to find without opening each lipstick.<br> SHANY is a proud member of PETA and all of our products are 100% cruelty-free. This (Not So) Sweet Sixteen Creme Lipstick Set was designed by beauty professionals in the USA.</p>",
            "Specs": "Size: 4.650\" X 4.650\" X 3.940\"",
            "By": "SHANYnation",
            "No": "upc-5",
            "Type": "type-category-upcoming-tcfhtml",
            "Best": "no",
            "Catename": "Upcoming Products"
        },
        {
            "Name": "Studio To Go Tabletop Makeup Station - RED",
            "Price": "250.00",
            "Des": "<p>The SHANY Studio To Go Tabletop Mirror Makeup Station is the perfect on-the-go accessory. Bring it along with you when traveling or use as a vanity at home. This beauty case is designed as a chic hardcover suitcase with two handles and locking clasps for security. The sleek yet durable design ensures damage protection from your case and its contents. Sits perfectly on flat tabletops and is easy to carry from place to place. With six studio lights (light bulbs included), this illuminating makeup station also comes with an 8 feet power cord, making it easy to use when working on clients. This case, measuring at 22 x 14.5 x 7 in., is the perfect gift for beginner makeup artists and seasoned professionals.</p>",
            "Features": "<p>Tabletop version of the Studio-To-Go light up makeup case and organizer, with locking keys, light bulbs, and power cord included.<br> Use durable case in place of a vanity, a makeup carrying case, cosmetics organizer, or as a lighted beauty train case when traveling.<br>Perfect size for carry-on luggage and comes with an extra outlet to connect to hair dryers, flat irons, and other electronic beauty items.<br> Measuring 22 x 14.5 x 7 in., this case is perfect to be used at cheerleader competitions, dance events, beauty pageants, and many other events.<br> SHANY is a proud member of PETA and all of our products are 100% cruelty-free. This tabletop makeup case was designed by beauty professionals in the USA.</p>",
            "Specs": "SKU: SH-CC0020-PK <br>WEIGHT: 21.2 lb",
            "By": "SHANYnation",
            "No": "upc-6",
            "Type": "type-category-upcoming-tcfhtml",
            "Best": "no",
            "Catename": "Upcoming Products"
        },
        {
            "Name": "Cosmetic Pencil Dual Sharpener",
            "Price": "10.00",
            "Des": "<p> The SHANY Cosmetic Pencil Sharpener is the perfect accessory to add to your makeup collection. With this custom sharpener, you will be able to bring your dull eyeliners and lip pencils back to life. Each side has a removable end to empty out shavings after each use, as well as allow for an easy clean up with a tool hidden inside to help. This makeup tool can be used with either the traditional wooden pencils or sleek plastic pencils. This small but powerful sharpener measures at 1.5 x 1 x 1 inches, which makes it small enough to travel with or add to your makeup collection. This SHANY makeup pencil sharpener was designed by beauty professionals in the USA.</p>",
            "Features": "<p>The SHANY makeup pencil dual sharpener is a staple to your makeup collection to bring your dulled down pencils back to life.<br> Open to reveal the printed sharpener with two openings for slim and jumbo pencils, along with a removable ends to catch any shavings.<br> This makeup tool is perfect to use with wooden or plastic makeup pencils and can be cleaned with the cleaning tool under the removable lid.<br> This small but powerful sharpener measures at 1.5 x 1 x 1 inches, making it easy to toss in your makeup travel bag or safely place in your makeup collection.<br> SHANY is a proud member of PETA and all of our products are 100% cruelty-free. This SHANY makeup pencil sharpener was designed by beauty professionals in the USA.</p>",
            "Specs": "Size: 1.400\" X 1.100\" X 1.000\"",
            "By": "SHANYnation",
            "No": "upc-7",
            "Type": "type-category-upcoming-tcfhtml",
            "Best": "no",
            "Catename": "Upcoming Products"
        }
    ];